import { Content } from "@google/genai";
import { Datum } from "./data";
import { Location, Region } from "./geo";

/**
 * An analysis of a single Datum against a particular Grant-Initiative pair
 * conducted as part of a GrantAnalysis.
 */
export type DatumAnalysis = {
  /**
   * The Datum that is the subject of this DatumAnalysis.
   */
  datum: Datum;

  /**
   * A short explanation of why this Datum was considered relevant to its
   * parent GrantAnalysis, or `null` if the user added it to that
   * GrantAnalysis manually.
   */
  relevance: string | null;

  /**
   * The actual content of this DatumAnalysis.
   *
   * @alpha
   * *The feature associated with this property is currently under review.*
   */
  result: {
    /**
     * An AI-generated explanation of the plain meaning of the Datum that
     * is the subject of this DatumAnalysis, structured as a list of
     * bullet points.
     */
    understand: string[];

    /**
     * One or more suggestions for how the Datum that is the subject of this
     * DatumAnalysis could be integrated into an application or report
     * prepared by the associated Initiative from the associated Grant.
     */
    apply: string[];
  };
};

/**
 * An abstract type that defines the properties shared by all
 * GrantAnalysis variants.
 */
export type BaseGrantAnalysis = {
  /**
   * The unique ID of this GrantAnalysis.
   */
  id: number;

  /**
   * The Location(s) that are relevant to this GrantAnalysis. (Does not include
   * Locations that are only implicitly relevant because they are present
   * within or more relevant Regions.)
   */
  locations: Location[];

  /**
   * The Region(s) that are relevant to this GrantAnalysis.
   */
  regions: Region[];

  /**
   * The DatumAnalysis instances that comprise this GrantAnalysis.
   */
  data: DatumAnalysis[];
};

/**
 * A GrantAnalysis conducted to help a specific Initiative prepare a
 * quantitatively strong application for a specific Grant.
 */
export type GrantWritingAnalysis = BaseGrantAnalysis;

/**
 * A single response generated by an AI system in conversation with an
 * Initiative concerning a single ReportingRequirement in a
 * GrantReportingAnalysis data gathering workflow.
 */
export type GrantReportConversationResponse = {
  /**
   * An AI-generated response to the user message that prompted the
   * generation of this GrantReportConversationResponse.
   */
  message: string;

  /**
   * A list of zero or more IDs of Datum instances that may help the Initiative
   * for which this GrantReportConversationResponse was generated satisfy the
   * associated ReportingRequirement. If the list contains at least two Datum
   * instance IDs, they will appear in order from most to least promising.
   */
  suggestions: number[];

  /**
   * For AI system use only; do not modify.
   * @internal
   * @readonly
   */
  is_sufficient: boolean;
};

/**
 * A complete record of a single conversation between an Initiative and an
 * AI system that concerns a single ReportingRequirement in a
 * GrantReportingAnalysis data gathering workflow.
 */
export type GrantReportingConversation = {
  /**
   * The unique ID of this GrantReportingConversation.
   */
  id: number;

  /**
   * The IDs of the initial set of Datum instance suggestions
   * generated for this GrantReportingConversation.
   *
   * @see {@link GrantReportConversationResponse.suggestions}
   */
  initialSuggestions: number[];

  /**
   * The complete Content of this GrantReportingConversation, including
   * all of the messages sent by both parties. The text Part of Content
   * items with a role of "model" will always contain JSON that
   * defines a GrantReportConversationResponse.
   *
   * @see {@link GrantReportConversationResponse}
   */
  content: Content[];

  /**
   * True if a user has marked this GrantReportingConversation as complete;
   * false otherwise.
   */
  markedComplete: boolean;
};

/**
 * A GrantAnalysis conducted to help a specific Initiative prepare a
 * quantitatively strong report about their use of an award that they have
 * received from a specific Grant.
 */
export type GrantReportingAnalysis = BaseGrantAnalysis & {
  /**
   * The GrantReportingConversations that comprise the data gathering workflow
   * for this GrantReportingAnalysis.
   *
   * @remarks
   * Each GrantReportingConversation concerns
   * one of the ReportingRequirements for the Grant that is the subject of this
   * GrantReportingAnalysis. As such, the items in this array appear in the
   * same order as their corresponding ReportingRequirements do in the
   * associated Grant object.
   *
   * Conversations are added to this array when a user views them for the first
   * time, so its length can be used to determine both the number of
   * ReportingRequirements that have been progressively disclosed and whether
   * they have all been encountered yet.
   */
  conversations: GrantReportingConversation[];
};

/**
 * An analysis of one or more Datum instances considered relevant to a specific
 * Grant that was conducted for and optionally contextualized by information
 * about a specific Initiative.
 */
export type GrantAnalysis = GrantWritingAnalysis | GrantReportingAnalysis;
